apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins
        ports:
        - containerPort: 8080
      - name: nginx
        image: nginx:1.16-alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: conf
        - mountPath: /var/log/nginx/access.log
          name: access-log
      volumes:
      - name: conf
        hostPath:
          # directory location on host
          path: /opt/nginx-conf/default.conf
          # this field is optional
          type: File
      - name: access-log
        hostPath:
          path: /opt/nginx-conf/access.log
          type: File

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
               - key: kubernetes.io/hostname
                 operator: In
                 values:
                 - k8s-worker-2
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k8s-worker-2