apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: tarasol-bi
  name: tarasol-bi
  namespace: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: tarasol-bi
  template:
    metadata:
      labels:
        app: tarasol-bi
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: tarasol-bi-configmap
        image: docker-registery.in3.cloud:5000/tarasol-bi:v3.1.0
        imagePullPolicy: Always
        name: tarasol-bi
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /app/dist/profiler-results
          name: profiler-results
      nodeSelector:
        beta.kubernetes.io/arch: amd46
      volumes:
      - name: profiler-results
        hostPath:
          # directory location on host
          path: /media/ext/profiler
          # this field is optional
          type: Directory  

