apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tarasol-pdf-editor
  name: tarasol-pdf-editor
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tarasol-pdf-editor
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tarasol-pdf-editor
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: tarasol-pdf-editor-configmap
        image: localhost:5000/tarasol-pdf-editor:v3.3.14
        imagePullPolicy: Always
        name: tarasol-pdf-editor
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
data:
kind: ConfigMap
metadata:
  name: tarasol-pdf-editor-configmap
  SYNCFUSION_LICENSE_KEY: Mzg1ODMzQDMxMzgyZTM0MmUzMGdFRGJvUno1MUx4Tit4S09CeS9xRHZzZU4ySVBjQVFuT0VpdWpHUWJ6aXM9


---
apiVersion: v1
kind: Service
metadata:
  name: tarasol-pdf-editor
spec:
  type: NodePort
  selector:
    app: tarasol-pdf-editor
  ports:
    - protocol: TCP
      port: 80